version: "3.9"

services:

  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
    ports:
      - "8080:8080"  # Порт для панели управления Traefik
      - "80:80"  # Порт для HTTP трафика
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - dev
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev"

  api:
    image: gadji1/online-chat:api-0.0.1
    volumes:
      - uploads:/app/storage/app/public
    networks:
      - dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.abakarov.store`)"
      - "traefik.http.services.api.loadbalancer.server.port=80"
      - "traefik.docker.network=dev"
      - "traefik.http.routers.api.entryPoints=http"

  panel:
    image: gadji1/online-chat:client-0.0.1
    networks:
      - dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`panel.abakarov.store`)"
      - "traefik.http.services.client.loadbalancer.server.port=80"
      - "traefik.docker.network=dev"
      - "traefik.http.routers.client.entryPoints=http"

  api-fast:
    image: gadji1/online-chat:api-fast-0.0.1
    volumes:
      - uploads:/app/storage/app/public
    networks:
      - dev

  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - dbVolume:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - "5432:5432"

networks:
  dev:
    name: dev

volumes:
  uploads:
  dbVolume:
    driver: local
  letsencrypt:  # Хранилище для сертификатов Let's Encrypt